# Generated by Django 2.2 on 2020-11-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200925_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['group__name', 'created_at']},
        ),
    ]
