# Generated by Django 2.2 on 2020-10-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
