# Generated by Django 2.2 on 2020-11-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['group__name', 'user__username', 'joined_at']},
        ),
        migrations.AddField(
            model_name='groupmember',
            name='joined_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
